sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  GOOGLE_APPLICATION_CREDENTIALS: .gcloud/keyfile.json
install:
  - docker pull cfranklin11/tipresias_data_science:latest
  - docker build --cache-from cfranklin11/tipresias_data_science:latest -t cfranklin11/tipresias_data_science:latest .
  - mkdir ${HOME}/.gcloud
  - openssl aes-256-cbc -K $encrypted_7fb3f8574845_key -iv $encrypted_7fb3f8574845_iv -in keyfile.json.enc -out ${HOME}/.gcloud/keyfile.json -d
jobs:
  include:
    - stage: test
      name: "Linting & Unit Tests"
      script:
        - docker run cfranklin11/tipresias_data_science:latest pylint --disable=R src main.py
        - docker run cfranklin11/tipresias_data_science:latest mypy src main.py
        - docker run cfranklin11/tipresias_data_science:latest pydocstyle src main.py
        - docker run -v "${HOME}/.gcloud:/app/.gcloud" -e CI=true -e GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS}" cfranklin11/tipresias_data_science:latest kedro test --no-cov src/tests/unit/
    - name: "Integration Tests"
      script:
        - sudo rm /usr/local/bin/docker-compose
        - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - docker-compose -f docker-compose.ci.yml run data_science kedro test --no-cov -n auto --dist=loadfile src/tests/integration
    - stage: deploy
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
        - docker push cfranklin11/tipresias_data_science:latest
        - ./scripts/deploy.sh
      name: "Deploy"
