sudo: required
services:
  - docker
env:
  global:
    DOCKER_COMPOSE_VERSION: 1.25.5
    GOOGLE_APPLICATION_CREDENTIALS: .gcloud/keyfile.json
    CC_TEST_REPORTER_ID: 3c6e7d3ecb1089284ed54da495ee9062362337415223df4c122dc68b575dd708
install:
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  # Install test coverage monitoring
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  # Pull & build image
  - docker pull cfranklin11/tipresias_data_science:latest
  - docker build --cache-from cfranklin11/tipresias_data_science:latest -t cfranklin11/tipresias_data_science:latest -f Dockerfile.local .
  # Set up authentication
  - openssl aes-256-cbc -K $encrypted_241002f0ef4b_key -iv $encrypted_241002f0ef4b_iv -in keyfile.json.enc -out keyfile.json -d
  - mkdir ${PWD}/.gcloud && mv keyfile.json ${GOOGLE_APPLICATION_CREDENTIALS}
  # Set up test coverage monitoring
  - ./cc-test-reporter before-build
script:
  # Linting & unit tests
  - docker run cfranklin11/tipresias_data_science:latest pip3 check
  - docker run cfranklin11/tipresias_data_science:latest pylint --disable=R src app.py scripts/save_default_models.py
  - docker run cfranklin11/tipresias_data_science:latest mypy src app.py scripts/save_default_models.py
  - docker run cfranklin11/tipresias_data_science:latest pydocstyle src app.py
  # Using pytest, because coverage.py doesn't play nice with the kedro CLI
  - docker run -v "${PWD}/.gcloud:/app/.gcloud" -v "${PWD}:/app" -e PYTHON_ENV=ci -e GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS}" cfranklin11/tipresias_data_science:latest coverage run -m pytest --no-cov src/tests/unit/
  # Integration tests
  # Using pytest, because coverage.py doesn't play nice with the kedro CLI
  - docker-compose -f docker-compose.ci.yml run data_science coverage run --append -m pytest --no-cov -n auto --dist=loadfile src/tests/integration
  # Code coverage
  # Running code coverage commands in scripts instead of after_script,
  # because after_script silently fails, and I don't check codeclimate often enough
  # to catch problems early.
  - docker-compose -f docker-compose.ci.yml run data_science coverage xml
  - ./cc-test-reporter format-coverage -t coverage.py
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
before_deploy:
  # Push docker image
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_data_science:latest
  # Prepare gcloud tool for deployment
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components install beta
  - gcloud --quiet components update
  - gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
  - gcloud --quiet config set project $PROJECT_ID
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: main
