sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.22.0
  GOOGLE_APPLICATION_CREDENTIALS: ./.gcloud/keyfile.json
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
before_script:
  - docker pull cfranklin11/tipresias_data_science:latest
  - docker pull cfranklin11/tipresias_afl_data:latest
  - docker build --cache-from cfranklin11/tipresias_data_science:latest -t cfranklin11/tipresias_data_science:latest .
jobs:
  include:
    - stage: "Test"
      script:
        - docker run cfranklin11/tipresias_data_science:latest pylint --disable=R src
        - docker run cfranklin11/tipresias_data_science:latest mypy src
        - docker-compose -f docker-compose.ci.yml run data_science kedro test --no-cov src/tests/unit/ src/tests/test_run.py
      name: "Linting & Unit Tests"
    - script:
        - docker-compose -f docker-compose.ci.yml run data_science kedro test --no-cov -n auto src/tests/integration
      name: "Integration Tests"
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_data_science:latest
  - mkdir $HOME/.gcloud
  - openssl aes-256-cbc -K $encrypted_88b6344ff4d0_key -iv $encrypted_88b6344ff4d0_iv -in keyfile.json.enc -out ${HOME}/.gcloud/keyfile.json -d
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
