version: "3.2"
services:
  data_science:
    image: cfranklin11/tipresias_data_science:latest
    volumes:
      - "${HOME}/.gcloud:/app/.gcloud"
    ports:
      - "8008:8008"
    depends_on:
      - afl_data
    environment:
      - AFL_DATA_SERVICE=${AFL_DATA_SERVICE}
      - CI=true
      - GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS}"
    command: python3 app.py
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    ports:
      - "8080:8080"
    command: Rscript app.R
