service: machine-learning

custom: ${file(./env.js):env}

provider:
  name: google
  stage: dev
  runtime: python37
  region: asia-east2
  memorySize: 1024
  timeout: "540s"
  project: ${self:custom.project}
  credentials: ${self:custom.credentials}
  environment:
    AFL_DATA_SERVICE: ${self:custom.afl_data_service}
    PYTHON_ENV: production
    GCPF_TOKEN: ${self:custom.gcpf_token}
    GCR_TOKEN: ${self:custom.gcr_token}
    PYTHONPATH: ./src

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - ./**
  include:
    - conf/**
    - src/augury/**
    - src/setup.py
    - main.py
    - package-lock.json
    - package.json
    - requirements.txt
    - .kedro.yml

functions:
  predictions:
    handler: predictions
    events:
      - http: path
  fixtures:
    handler: fixtures
    events:
      - http: path
  match_results:
    handler: match_results
    events:
      - http: path
  ml_models:
    handler: ml_models
    events:
      - http: path
